// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function emptyLane() {
  return /* record */[
          /* values */Caml_array.caml_make_vect(16, 0),
          /* index */0,
          /* length */8
        ];
}

function advance(lane) {
  var match = (lane[/* index */1] + 1 | 0) >= lane[/* length */2];
  return /* record */[
          /* values */lane[/* values */0],
          /* index */match ? 0 : lane[/* index */1] + 1 | 0,
          /* length */lane[/* length */2]
        ];
}

exports.emptyLane = emptyLane;
exports.advance = advance;
/* No side effect */
