// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Lane");

function make(label, lane, onClick, onSetLength, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("p", undefined, label), React.createElement("div", {
                              className: "flex"
                            }, $$Array.mapi((function (i, value) {
                                    var match = i >= lane[/* length */2];
                                    var match$1 = lane[/* index */1] === i;
                                    var match$2 = lane[/* index */1] === i;
                                    return React.createElement("div", {
                                                key: String(i),
                                                className: "w2 relative " + (
                                                  match ? "o-50" : ""
                                                )
                                              }, React.createElement("button", {
                                                    className: "input-reset db w-100 h1 " + (
                                                      match$1 ? "bg-red" : "bg-gray"
                                                    ),
                                                    onClick: (function () {
                                                        return Curry._2(onClick, i, value + 1 | 0);
                                                      })
                                                  }), React.createElement("button", {
                                                    className: "input-reset db w-100 h1 " + (
                                                      match$2 ? "bg-red" : "bg-gray"
                                                    ),
                                                    onClick: (function () {
                                                        return Curry._2(onClick, i, value - 1 | 0);
                                                      })
                                                  }), React.createElement("p", {
                                                    className: "relative tc ma0"
                                                  }, String(value)), React.createElement("button", {
                                                    className: "input-reset db w-100 h1",
                                                    onClick: (function () {
                                                        return Curry._1(onSetLength, i);
                                                      })
                                                  }));
                                  }), lane[/* values */0])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
